# Use Node 20 or above (required by @hrms/shared)
FROM node

# Set working directory
WORKDIR /app

# Copy only package files first for efficient caching
COPY package*.json ./
COPY hrms-shared-0.1.0.tgz ./hrms-shared-0.1.0.tgz

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose your app port
EXPOSE 4003

# Start the app
CMD ["npm", "start"]
